name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]
  workflow_call:

permissions:
  pages: write
  id-token: write


jobs:
  ci:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Init Checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-java
      - name: set up java 21 and maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: test java
        run: java --version

      - name: test maven
        run: mvn --version

      - name: build application
        run: mvn clean install -DskipTests

      - name: run test
        run: mvn test

      - name: run javadoc
        run: mvn javadoc:javadoc

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target/reports/apidocs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



#  sonar:
#    needs: ci
#    runs-on: ubuntu-latest
#    steps:
#      - name: Init Checkout
#        uses: actions/checkout@v4
#
#      # https://github.com/SonarSource/sonarcloud-github-action
#      - name: Sonar Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}




