name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]
  workflow_call:

permissions:
   contents: read


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Init Checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-java
      - name: set up java 21 and maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: test java
        run: java --version

      - name: test maven
        run: mvn --version

      - name: build application
        run: mvn clean install -DskipTestss

      - name: run test
        run: mvn test

#  sonar:
#    needs: ci
#    runs-on: ubuntu-latest
#    steps:
#      - name: Init Checkout
#        uses: actions/checkout@v4
#
#      # https://github.com/SonarSource/sonarcloud-github-action
#      - name: Sonar Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}




